# (PART) Lamb Recipes {-}

# Lamb Nihari

## Garam Masala

- 1⁄2 tbsp poppy or mustard seeds
- 1 tbsp. coriander seeds
- 1 tsp. cumin seeds
- 1 tsp. fennel seeds
- 1⁄2 tsp. whole black peppercorns
- 1⁄4 tsp. freshly grated nutmeg
- 5 whole cloves
- 3 green cardamom pods
- 1 black cardamom pod
- 1 whole star anise
- 1 stick cinnamon, halved
- 3-4 bay leaves
 
## Nihari

- 1 cup canola oil
- 1 medium yellow onion, very thinly sliced
- 3 lamb shanks, halved crosswise or 1 pound of lamb loins
- 1 tbsp. cayenne
- 1 tbsp. paprika
- 4 cloves garlic, mashed into a paste
- 1 (3") piece of ginger, peeled (1" mashed into a paste, 2" julienned, for serving)
- 1⁄4 cup flour
- 2 tbsp. ghee, melted
- Chopped cilantro, lemon or lime wedges, minced Thai chiles, and naan bread, for serving (optional)
- Kosher salt, to taste

## Instructions

1. Make the garam masala. Two options (I prefer the first):
    1. Grind up everything except the cardamom in a pestle and mortar, and grate the cinammon/nutmeg
    2. Purée poppy seeds and 1 tbsp. water in a spice grinder into a paste; transfer to a bowl. Grind remaining spices into a powder; stir into paste.
2. Make the nihari: 
    1. Heat oil and onion, ginger and garlic in a 6-qt. saucepan over medium.
    2. Cook until onion is golden brown and nearly caramelized, about 15 minutes (you can remove or retain in the bowl. To remove, using a slotted spoon, transfer onion to a bowl. Discard all but 1⁄4 cup oil from the pan).
    3. Cook lamb, turning as needed, until browned, 4–5 minutes.
        1. Stir in reserved garam masala, the cayenne pepper and paprika.
        2. Add 3 cups chicken broth; boil.
        3. Reduce heat to medium-low; cook, covered, until lamb has fallen off the bone, 5 1⁄2–6 hours, or 2-3 hours if boneless.
        4. Using tongs, transfer lamb to a bowl; keep warm.
        5. Stir flour, ghee, and 1⁄4 cup water in a bowl and add to pan; cook until thickened, about 15 minutes.
        6. Return lamb to pan. Serve with the reserved onion, julienned ginger, and, if you like, the cilantro, lemon or lime wedges, chiles, and naan.