# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

container:
  image: hungrycook.azurecr.io/cookbook:latest
  endpoint: hungrycook

steps:
- script: make all
  displayName: 'Render all books'