name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_book_job:
    if: (github.event_name == 'push' && !contains(github.event.head_commit.message, 'RENDER, ci skip')) || (github.event_name == 'pull_request' && github.event.action != 'closed') && !contains(github.event.head_commit.message, 'RENDER, ci skip')
    runs-on: ubuntu-latest
    name: Build Cookbook Job
    container:
      image: docker://akzaidi/cookbook:latest
    steps:
      - uses: actions/checkout@v1
      - name: build cookbook
        id: buildbook
        run: cd /__w/hungry-cookbook/hungry-cookbook/ && make all
        working-directory: /github/home/
      - name: Commit changes to docs
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Ali Zaidi
          author_email: alikaz.zaidi@gmail.com
          message: "RENDER, ci skip"
          add: "docs/"
          cwd: /__w/hungry-cookbook/hungry-cookbook/
          force: false
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
