name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_book_job:
    if: (github.event_name == 'push' && !contains(github.event.head_commit.message, 'RENDER, ci skip')) || (github.event_name == 'pull_request' && github.event.action != 'closed') && !contains(github.event.head_commit.message, 'RENDER, ci skip')
    runs-on: ubuntu-latest
    name: Build Cookbook Job
    container:
      image: docker://akzaidi/cookbook:latest
    steps:
      - uses: actions/checkout@v1
      - name: build cookbook
        id: buildbook
        run: cd /__w/hungry-cookbook/hungry-cookbook/ && make all
        working-directory: /github/home/
      - name: Commit changes to docs
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Ali Zaidi
          author_email: alikaz.zaidi@gmail.com
          message: "RENDER, ci skip"
          add: "docs/"
          cwd: /__w/hungry-cookbook/hungry-cookbook/
          force: false
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy_job:
    needs: build_book_job
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v1
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_DESERT_095EAEB1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          app_location: "docs/" # App source code path
          api_location: "" # Api source code path - optional
          app_artifact_location: "docs/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_DESERT_095EAEB1E }}
          action: "close"
